/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include  <android/log.h>
/* Header for class com_example_dzj_android_practice_jnidemo_JniTest */
#define TAG "wzx"
// 定义info信息
#define LOGI(...) __android_log_print(ANDROID_LOG_INFO,TAG,__VA_ARGS__)
// 定义debug信息
#define LOGD(...) __android_log_print(ANDROID_LOG_DEBUG, TAG, __VA_ARGS__)
// 定义error信息
#define LOGE(...) __android_log_print(ANDROID_LOG_ERROR,TAG,__VA_ARGS__)
#ifndef _Included_com_example_dzj_android_practice_jnidemo_JniTest
#define _Included_com_example_dzj_android_practice_jnidemo_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_dzj_android_practice_jnidemo_JniTest
 * Method:    nativeFunc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_dzj_android_1practice_jnidemo_JniTest_nativeFunc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
